version: "3.8"
services:
  watchtower:
    image: containrrr/watchtower
    environment:
      DOCKER_CONFIG: /config
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/watchtower/config/:/config/
    command: --interval 120
