name: deploy-blockchain
on:
  push:
    branches:
      - round-1

env:
  CHAIN_IMAGE_NAME: u18-eth-chain
jobs:
  build-chain:
    name: Build chain image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build . --file Dockerfile --tag $CHAIN_IMAGE_NAME ghcr.io/${{ github.repository_owner }}/$CHAIN_IMAGE_NAME:latest --label "runnumber=${GITHUB_RUN_ID}"
        working-directory: infra/blockchain
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Push image
        run: docker push ghcr.io/${{ github.repository_owner }}/$CHAIN_IMAGE_NAME:latest
  test-and-deploy-contracts:
    name: Deploy blockchain contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Test "My Secret Note" challenge
        working-directory: ./Blockchain/my-secret-note
        run: |
          forge --version
          forge test -vvv
        id: test-my-secret-note
      - name: Deploy "My Secret Note" challenge
        working-directory: ./Blockchain/my-secret-note
        run: forge create --rpc-url ${{ vars.BLOCKCHAIN_RPC_URL }} --private-key ${{ secrets.BLOCKCHAIN_CONTRACT_DEPLOYER_PRIVATE_KEY }} src/Notebin.sol:Notebin
      - name: Test "Bake Danuki" challenge
        working-directory: ./Blockchain/bake-danuki/contract
        run: |
          forge --version
          forge test -vvv
        id: test-bake-danuki
      - name: Deploy "Bake Danuki" challenge
        working-directory: ./Blockchain/bake-danuki/contract
        run: forge create --rpc-url ${{ vars.BLOCKCHAIN_RPC_URL }} --private-key ${{ secrets.BLOCKCHAIN_CONTRACT_DEPLOYER_PRIVATE_KEY }} src/BakeDanuki.sol:BakeDanuki
      - name: Test "Flag Market" challenge
        working-directory: ./Blockchain/flag-market/contract
        run: |
          forge --version
          forge test -vvv
        id: test-flag-market
      - name: Deploy "Flag Market" challenge
        working-directory: ./Blockchain/flag-market/contract
        run: forge create --rpc-url ${{ vars.BLOCKCHAIN_RPC_URL }} --private-key ${{ secrets.BLOCKCHAIN_CONTRACT_DEPLOYER_PRIVATE_KEY }} src/FlagMarket.sol:FlagMarket
