name: deploy-my-secret-note
on:
  push:
    paths:
      - "blockchain/my-secret-note/**"
jobs:
  deploy-my-secret-note:
    name: Deploy "My Secret Note" contract and flag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Test "My Secret Note" challenge
        working-directory: ./Blockchain/my-secret-note
        run: |
          forge --version
          forge test -vvv
        id: test-my-secret-note
      - name: Deploy "My Secret Note" challenge
        working-directory: ./Blockchain/my-secret-note
        run: forge create --rpc-url ${{ vars.BLOCKCHAIN_RPC_PUBLIC_URL }} --private-key ${{ secrets.BLOCKCHAIN_CONTRACT_DEPLOYER_PRIVATE_KEY }} src/Notebin.sol:Notebin
      - name: Deploy "My Secret Note" flag
        run: cast call ${{ vars.BLOCKCHAIN_MY_SECRET_NOTE_ADDRESS }} "setNote(string)()" "${{ vars.BLOCKCHAIN_MY_SECRET_NOTE_FLAG }}" --rpc-url ${{ vars.BLOCKCHAIN_RPC_PUBLIC_URL }}
