name: deploy-blockchain
on:
  push:
    branches:
      - round-1
jobs:
  test-and-deploy-blockchain:
    strategy:
      fail-fast: true
    name: Deploy blockchain challenges
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Test "My Secret Note" challenge
        working-directory: ./Blockchain/my-secret-note
        run: |
          forge --version
          forge test -vvv
        id: test-my-secret-note
      - name: Deploy "My Secret Note" challenge
        working-directory: ./Blockchain/my-secret-note
        run: /
          forge create --rpc-url https://eth.u18.haruulzangi.mn --private-key ${{ secrets.BLOCKCHAIN_CONTRACT_DEPLOYER_PRIVATE_KEY }} src/Notebin.sol:Notebin
      - name: Test "Bake Danuki" challenge
        working-directory: ./Blockchain/bake-danuki/contract
        run: |
          forge --version
          forge test -vvv
        id: test-my-secret-note
      - name: Deploy "Bake Danuki" challenge
        working-directory: ./Blockchain/bake-danuki/contract
        run: /
          forge create --rpc-url https://eth.u18.haruulzangi.mn --private-key ${{ secrets.BLOCKCHAIN_CONTRACT_DEPLOYER_PRIVATE_KEY }} src/BakeDanuki.sol:BakeDanuki

