name: deploy-blockchain
on:
  push:
    branches:
      - round-1

jobs:
  build-chain:
    name: Build chain image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/u18-eth-chain:latest --label "runnumber=${GITHUB_RUN_ID}"
        working-directory: infra/blockchain
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Push image
        run: docker push ghcr.io/${{ github.repository_owner }}/u18-eth-chain:latest
  test-and-deploy-contracts:
    name: Deploy blockchain contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Test "My Secret Note" challenge
        working-directory: ./Blockchain/my-secret-note
        run: |
          forge --version
          forge test -vvv
        id: test-my-secret-note
      - name: Deploy "My Secret Note" challenge
        working-directory: ./Blockchain/my-secret-note
        run: forge create --rpc-url ${{ vars.BLOCKCHAIN_RPC_PUBLIC_URL }} --private-key ${{ secrets.BLOCKCHAIN_CONTRACT_DEPLOYER_PRIVATE_KEY }} src/Notebin.sol:Notebin
      - name: Test "Bake Danuki" challenge
        working-directory: ./Blockchain/bake-danuki/contract
        run: |
          forge --version
          forge test -vvv
        id: test-bake-danuki
      - name: Deploy "Bake Danuki" challenge
        working-directory: ./Blockchain/bake-danuki/contract
        run: forge create --rpc-url ${{ vars.BLOCKCHAIN_RPC_PUBLIC_URL }} --private-key ${{ secrets.BLOCKCHAIN_CONTRACT_DEPLOYER_PRIVATE_KEY }} src/BakeDanuki.sol:BakeDanuki
      - name: Test "Flag Market" challenge
        working-directory: ./Blockchain/flag-market/contract
        run: |
          forge --version
          forge test -vvv
        id: test-flag-market
      - name: Deploy "Flag Market" challenge
        working-directory: ./Blockchain/flag-market/contract
        run: forge create --rpc-url ${{ vars.BLOCKCHAIN_RPC_PUBLIC_URL }} --private-key ${{ secrets.BLOCKCHAIN_CONTRACT_DEPLOYER_PRIVATE_KEY }} src/FlagMarket.sol:FlagMarket
  build-web-services:
    name: Build web services
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      # Bake Danuki
      - name: Build dotenv file for "Bake Danuki" flag guard
        run: |
          echo RPC_URL=${{ vars.BLOCKCHAIN_RPC_URL }} > .env
          echo CONTRACT_ADDRESS=${{ vars.BLOCKCHAIN_BAKE_DANUKI_ADDRESS }} >> .env
          echo FLAG=${{ vars.BLOCKCHAIN_BAKE_DANUKI_FLAG }} >> .env
        working-directory: Blockchain/bake-danuki/flag-guard
      - name: Build "Bake Danuki" flag guard image
        run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/bake-danuki-flag-guard:latest --label "runnumber=${GITHUB_RUN_ID}"
        working-directory: Blockchain/bake-danuki/flag-guard
      - name: Push "Bake Danuki" flag guard image
        run: docker push ghcr.io/${{ github.repository_owner }}/bake-danuki-flag-guard:latest
      # Flag Market
      - name: Build dotenv file for "Flag Market" flag guard
        run: |
          echo RPC_URL=${{ vars.BLOCKCHAIN_RPC_URL }} > .env
          echo CONTRACT_ADDRESS=${{ vars.BLOCKCHAIN_FLAG_MARKET_ADDRESS }} >> .env
          echo FLAG=${{ vars.BLOCKCHAIN_FLAG_MARKET_FLAG }} >> .env
        working-directory: Blockchain/flag-market/flag-guard
      - name: Build "Flag Market" flag guard image
        run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/flag-market-guard:latest --label "runnumber=${GITHUB_RUN_ID}"
        working-directory: Blockchain/flag-market/flag-guard
      - name: Push "Flag Market" flag guard image
        run: docker push ghcr.io/${{ github.repository_owner }}/flag-market-guard:latest
      # Faucet
      - name: Build dotenv file for faucet
        run: |
          echo RPC_URL=${{ vars.BLOCKCHAIN_RPC_URL }} > .env
          echo FAUCET_PRIVATE_KEY=${{ secrets.BLOCKCHAIN_FAUCET_PRIVATE_KEY }} >> .env
        working-directory: Blockchain/faucet
      - name: Build faucet image
        run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/faucet:latest --label "runnumber=${GITHUB_RUN_ID}"
        working-directory: Blockchain/faucet
      - name: Push faucet image
        run: docker push ghcr.io/${{ github.repository_owner }}/faucet:latest
      # Who Are You
      - name: Build dotenv file for "Who Are You" challenge
        run: echo FLAG=${{ vars.BLOCKCHAIN_WHO_ARE_YOU_FLAG }} > .env
        working-directory: Blockchain/who-are-you
      - name: Build "Who Are You" flag guard image
        run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/who-are-you:latest --label "runnumber=${GITHUB_RUN_ID}"
        working-directory: Blockchain/who-are-you
      - name: Push "Who Are You" flag guard image
        run: docker push ghcr.io/${{ github.repository_owner }}/who-are-you:latest
