name: deploy-blockchain
on:
  push:
    branches:
      - round-1
jobs:
  build-chain:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./infra/blockchain
          push: true
          tags: haruulzangi/eth-chain:latest
  test-and-deploy-contracts:
    name: Deploy blockchain contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Test "My Secret Note" challenge
        working-directory: ./Blockchain/my-secret-note
        run: |
          forge --version
          forge test -vvv
        id: test-my-secret-note
      - name: Deploy "My Secret Note" challenge
        working-directory: ./Blockchain/my-secret-note
        run: forge create --rpc-url ${{ vars.BLOCKCHAIN_RPC_URL }} --private-key ${{ secrets.BLOCKCHAIN_CONTRACT_DEPLOYER_PRIVATE_KEY }} src/Notebin.sol:Notebin
      - name: Test "Bake Danuki" challenge
        working-directory: ./Blockchain/bake-danuki/contract
        run: |
          forge --version
          forge test -vvv
        id: test-bake-danuki
      - name: Deploy "Bake Danuki" challenge
        working-directory: ./Blockchain/bake-danuki/contract
        run: forge create --rpc-url ${{ vars.BLOCKCHAIN_RPC_URL }} --private-key ${{ secrets.BLOCKCHAIN_CONTRACT_DEPLOYER_PRIVATE_KEY }} src/BakeDanuki.sol:BakeDanuki
      - name: Test "Flag Market" challenge
        working-directory: ./Blockchain/flag-market/contract
        run: |
          forge --version
          forge test -vvv
        id: test-flag-market
      - name: Deploy "Flag Market" challenge
        working-directory: ./Blockchain/flag-market/contract
        run: forge create --rpc-url ${{ vars.BLOCKCHAIN_RPC_URL }} --private-key ${{ secrets.BLOCKCHAIN_CONTRACT_DEPLOYER_PRIVATE_KEY }} src/FlagMarket.sol:FlagMarket
