version: "3.8"
services:
  massignment:
    image: ghcr.io/haruulzangi/massignment:latest
    volumes:
      - ./massignment/data:/data:rw
    environment:
      - DB_DIR=/data
    networks: [traefik_proxy]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.massignment-http.entrypoints=web"
      - "traefik.http.routers.massignment-http.rule=Host(`massignment.challenge.haruulzangi.mn`)"
      - "traefik.http.routers.massignment-http.middlewares=massignment-https"
      - "traefik.http.middlewares.massignment-https.redirectscheme.scheme=https"
      - "traefik.http.routers.massignment.entrypoints=websecure"
      - "traefik.http.routers.massignment.rule=Host(`massignment.challenge.haruulzangi.mn`)"
      - "traefik.http.routers.massignment.tls=true"
      - "traefik.http.routers.massignment.tls.certresolver=resolver"
  russian-radio:
    image: ghcr.io/haruulzangi/russian-radio:latest
    networks: [traefik_proxy]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.russian-radio-http.entrypoints=web"
      - "traefik.http.routers.russian-radio-http.rule=Host(`russian-radio.challenge.haruulzangi.mn`)"
      - "traefik.http.routers.russian-radio-http.middlewares=russian-radio-https"
      - "traefik.http.middlewares.russian-radio-https.redirectscheme.scheme=https"
      - "traefik.http.routers.russian-radio.entrypoints=websecure"
      - "traefik.http.routers.russian-radio.rule=Host(`russian-radio.challenge.haruulzangi.mn`)"
      - "traefik.http.routers.russian-radio.tls=true"
      - "traefik.http.routers.russian-radio.tls.certresolver=resolver"
  demon-slayer:
    image: ghcr.io/haruulzangi/demon-slayer:latest
    networks: [traefik_proxy]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.demon-slayer-http.entrypoints=web"
      - "traefik.http.routers.demon-slayer-http.rule=Host(`demon-slayer.challenge.haruulzangi.mn`)"
      - "traefik.http.routers.demon-slayer-http.middlewares=demon-slayer-https"
      - "traefik.http.middlewares.demon-slayer-https.redirectscheme.scheme=https"
      - "traefik.http.routers.demon-slayer.entrypoints=websecure"
      - "traefik.http.routers.demon-slayer.rule=Host(`demon-slayer.challenge.haruulzangi.mn`)"
      - "traefik.http.routers.demon-slayer.tls=true"
      - "traefik.http.routers.demon-slayer.tls.certresolver=resolver"
networks:
  traefik_proxy:
    external: true
