version: "3.8"
services:
  russian-radio:
    image: ghcr.io/haruulzangi/russian-radio:latest
    networks: [traefik_proxy]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.russian-radio-http.entrypoints=web"
      - "traefik.http.routers.russian-radio-http.rule=Host(`russian-radio.challenge.haruulzangi.mn`)"
      - "traefik.http.routers.russian-radio-http.middlewares=russian-radio-https"
      - "traefik.http.middlewares.russian-radio-https.redirectscheme.scheme=https"
      - "traefik.http.routers.russian-radio.entrypoints=websecure"
      - "traefik.http.routers.russian-radio.rule=Host(`russian-radio.challenge.haruulzangi.mn`)"
      - "traefik.http.routers.russian-radio.tls=true"
      - "traefik.http.routers.russian-radio.tls.certresolver=resolver"
networks:
  traefik_proxy:
    external: true
